[package]
name = "lud"
version = "0.2.0"
authors = ["Joshua Crowgey <jcrowgey@uw.edu>"]
edition = "2018"

[dependencies]
byteorder = "*"
clap = "*"
rand = "*"

[target.'cfg(linux)'.dependencies]
resolv-conf = "0.6.2"

[target.'cfg(windows)'.dependencies]
ipconfig = "0.2.1"
